image: alpine:latest

pages:
  stage: deploy
  script:
    - apk add --no-cache bash
    - mkdir .public
    - cp -r gitlab/* .public
  artifacts:
    paths:
      - .public
    expire_in: 1 week
  only:
    - main
